"""item identifiers, drop lens image url

Revision ID: ec4d3c87e88d
Revises: 25763ed9ff7f
Create Date: 2026-09-13 16:30:41.718076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec4d3c87e88d'
down_revision: Union[str, Sequence[str], None] = '25763ed9ff7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('identifiers', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.drop_column('items', 'search_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('search_image_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('items', 'identifiers')
    # ### end Alembic commands ###
