"""live search schema

Revision ID: 25763ed9ff7f
Revises: 
Create Date: 2026-09-13 15:48:53.914956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25763ed9ff7f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('upload', 'url', name='item_source', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('image_key', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('search_image_url', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('retailer', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prices_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('visual_match', 'aesthetic', 'similar_brand', 'offer', name='listing_kind', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('group_label', sa.String(length=200), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('retailer', sa.String(length=200), nullable=True),
    sa.Column('retailer_icon', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('shipping', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('condition', sa.String(length=64), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviews', sa.Integer(), nullable=True),
    sa.Column('match_reason', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'kind', 'url')
    )
    op.create_index('ix_listings_item_kind', 'listings', ['item_id', 'kind'], unique=False)
    op.create_table('saved_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('list', sa.Enum('bag', 'wishlist', name='saved_list', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('retailer', sa.String(length=200), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'list', 'url')
    )
    op.create_index(op.f('ix_saved_items_client_id'), 'saved_items', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_items_client_id'), table_name='saved_items')
    op.drop_table('saved_items')
    op.drop_index('ix_listings_item_kind', table_name='listings')
    op.drop_table('listings')
    op.drop_table('items')
    # ### end Alembic commands ###
