"""ranking signals and item embeddings

Revision ID: 74fcd6aba237
Revises: ec47dfe43d4c
Create Date: 2026-09-14 22:49:33.101207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74fcd6aba237'
down_revision: Union[str, Sequence[str], None] = 'ec47dfe43d4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('image_embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('listings', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('listings', sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'signals')
    op.drop_column('listings', 'score')
    op.drop_column('items', 'image_embedding')
    # ### end Alembic commands ###
