"""initial schema

Revision ID: 85ecd00eb099
Revises: 
Create Date: 2026-09-13 15:26:10.503420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85ecd00eb099'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspirations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('image_key', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('aesthetic_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('tagline', sa.String(length=200), nullable=False),
    sa.Column('accent_color', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('boards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inspiration_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('aesthetic_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspiration_id'], ['inspirations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('category', sa.Enum('top', 'bottom', 'dress', 'outerwear', 'footwear', 'bag', 'accessory', name='category', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('subcategory', sa.String(length=64), nullable=True),
    sa.Column('base_color', sa.String(length=32), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('image_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_cents >= 0', name='price_non_negative'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'source_id')
    )
    op.create_index('ix_products_image_embedding_hnsw', 'products', ['image_embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'image_embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_products_source_id'), 'products', ['source_id'], unique=False)
    op.create_index('ix_products_store_category', 'products', ['store_id', 'category'], unique=False)
    op.create_table('board_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_id', 'position')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board_items')
    op.drop_index('ix_products_store_category', table_name='products')
    op.drop_index(op.f('ix_products_source_id'), table_name='products')
    op.drop_index('ix_products_image_embedding_hnsw', table_name='products', postgresql_using='hnsw', postgresql_ops={'image_embedding': 'vector_cosine_ops'})
    op.drop_table('products')
    op.drop_table('boards')
    op.drop_table('stores')
    op.drop_table('inspirations')
    # ### end Alembic commands ###
